services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:Almaty111@host.docker.internal:5432/lol
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Almaty111
      POSTGRES_DB: lol
    ports:
      - "5432:5432"
